### ISSUE TITLE
Filtering Criteria Inputs

### ISSUE THREAD

**Issue by jbranigan** [cartodb-org/cartodb#11]
- Criteria inputs would be
  - Begins with
  - Contains
  - Ends with
  - Equals
- Text field following the Criteria input for Text Fields
- Ability to add or remove rows

**Comment by mbforr** [comment]
![screen shot 2016-02-10 at 11 37 58 am](https://cloud.githubusercontent.com/assets/4828460/12954053/036a6314-cfeb-11e5-8a44-4e1777cc4ae1.png)
