### ISSUE TITLE
[ALIASES] Remove N/S Icons from filter dropdown

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#131]
We should remove N/S icons from filter dropdown:

![screen shot 2017-03-03 at 19 34 01](https://cloud.githubusercontent.com/assets/4222826/23563772/6b2d0d38-0048-11e7-9e67-6d50b370ab66.png)

**Comment by coyle5280** [comment]
This issue has been resolved.  Removed the span from the template. 
![image](https://cloud.githubusercontent.com/assets/11877788/23569239/7928f352-001b-11e7-8f97-eb10d94a31f2.png)
