### ISSUE TITLE
[ALIASES] Hide aliasing behind feature flag

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#132]
Make aliasing feature available only to users with `aliases` feature flag enabled.

## Notes

To add a feature flag in your environment, go to the Rails app root dir and:

```bash
bundle exec rake cartodb:features:add_feature_flag['aliases']
rake cartodb:features:enable_feature_for_user['aliases',<username>]
```

**Comment by coyle5280** [comment]
Only users with the aliases feature flag are now able to edit, remove or add aliases to column names and table titles.
