### ISSUE TITLE
[ALIASES] Fix Sugar lib issue on filter dropdown

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#135]
## Steps to reproduce:

1. Have a dataset with an alias that contains underscores (i.e.: `biking_routes_city`)
2. Open side panel
3. Click on the dropdown labeled "select a column..."

## Expected result:

The dropdown displays column names and aliases, beautified if necessary.

## Actual result:

An error trace saying "Sugar" is not defined.

**Comment by coyle5280** [comment]
#137 Pull request for Sugar Bug Fix.  Was able to reproduce before and after. Should be fixed.
