### ISSUE TITLE
[ALIASES] Show aliasing options only from table view, not map view

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#142]
## STR

(with a aliases feature flag enabled user)

1. Crate a map from an uploaded dataset (not sync table)
2. Access the Map from the maps dashboard
3. Go "table" view inside the map

## Expected result

The user can't edit aliases

## Actual result

The user can edit aliases

**Comment by coyle5280** [comment]
See PR #143 

## Changes
Made change to `table.js` and `table_header_options.jst.ejs` and added a check to see if vis is in table mode. 

Please test and let me know if any further changes are needed.

Thanks!
