### ISSUE TITLE
[ALIASES] Fix column renaming for normal users

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#149]
# STR:

1. Normal user (no `aliases` feature flag) uploads dataset
2. Create map with dataset
3. Get into table view in created map
4. Rename column

# Expected behaviours:

Column gets renamed

# Actual behaviour

No popup for rename appears.

**Comment by gfiorav** [comment]
Pr off source please

**Comment by gfiorav** [comment]
Hey Josh, be sure to leave a status update here before leaving for the day :)

**Comment by coyle5280** [comment]
# Update
After looking at the code I feel that we should be able to adjust the logic in the template to handle the needed change.  The file `table_header_view.jst.ejs` is where the changes need to be made to fix the column name change bug.  The `<input class="col_name_edit" type="text" value="<%- col_name %>" />` is in the `if (hasAliasesFeatureFlag)` check and this is preventing a non data user from changing the column name.

**Comment by coyle5280** [comment]
see PR #155 

Let me know if you find any errors in testing. Thanks

**Comment by coyle5280** [comment]
I have completed the changes that you requested! Thanks.  Let me know if any further changes are needed.
