### ISSUE TITLE
[ALIASES] Make aliased table names appear in dataset's dashboard

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#152]
When accessing the datasets dashboard, the dataset names should be aliased if an alias was set for them. Only the alias should show, not the original table name.

**Comment by gfiorav** [comment]
Hey @coyle5280, take care of this issue before fixing the rename please!

**Comment by coyle5280** [comment]
See PR #154 

# Changes
Standard User should see alias table name in dashboard view if table has been given an alias.
Dataset or map user should see both an alias name and an original table name in dashboard view
