### ISSUE TITLE
[ALIASES] Show aliased names in "Browse" modal

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#156]
## STR

1. Go into a map
2. On the top left, hit on browse (see screenshot)

![e71e9a90-0b08-11e7-9804-b1cc521046ae](https://cloud.githubusercontent.com/assets/4222826/24055124/2b485838-0b3f-11e7-94af-08e0c302557a.PNG)

## Expected result

The datasets appear, with their aliased names if needed (and parenthesis original if maps data user)

## Actual result

The datasets are not aliased

![josh](https://cloud.githubusercontent.com/assets/4222826/24055445/55d6130a-0b40-11e7-9d46-b76fbf3ea6b0.gif)

**Comment by coyle5280** [comment]
See PR #157 

I wasn't sure of the exact usage for the remote data sets so I added the same code to display the original table name if it was needed but I can remove this if it was added incorrectly.  Let me know.  Thanks
