### ISSUE TITLE
[ALIASES] Hide original dataset name for non-alias users

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#158]
## Context

We had originally spoken about having the original table name show (in parenthesis) for all users. We argued that it's need for custom SQLs. Normal users won't get the chance to modify the SQL, so no need for it. We should remove it (unless the user has the feature flag `aliases` enabled).

Let me know if you have any questions!

**Comment by coyle5280** [comment]
See PR #159 

Let me know if you want any changes. Thanks
