### ISSUE TITLE
[ALIASES] Aliased dataset names not present in Delete dialogs

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#161]
## STR

1. Create a dataset
2. Add an alias to the dataset's name
3. Go back to dashboard
4. Select precious dataset and click on "Delete"

## Expected result

The warning dialog or confirmation dialogs appear warning about the dataset deletion, using it's aliased name.

## Actual result

The warning dialog or confirmation dialogs appear warning about the dataset deletion, using it's original name.

For example, this is for the confirmation dialog:

![screen shot 2017-04-05 at 17 08 16](https://cloud.githubusercontent.com/assets/4222826/24712396/06783224-1a23-11e7-9373-761ac492f740.png)

**Comment by coyle5280** [comment]
Should be good to go. If you see any issues please let me know.
