### ISSUE TITLE
[ALIASES] "Confirm delete column" modal show's original column name instead of alias

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#163]
## STR

1. Create an alias for a column in a dataset
2. Click on "Delete column"

## Expected result

A confirmation modal comes up prompting for confirmation on deleting the column, using it's alias.

## Actual result

The confirmation modal shows the original column name, not the aliased name.

Thanks for reporting @coyle5280 !

**Comment by coyle5280** [comment]
This should be good. All seems to be working as expected but let me know if anything needs to be changed.

**Comment by coyle5280** [comment]
I have made changes to address the issues that you raised.  Please review the changes in the PR and let me know if you have any questions.
