### ISSUE TITLE
Default "Analyse" column load creates SQL API errors

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#170]
# STR

1. Create a map
2. Apply an "Analyse" wizard (for example "Choropleth")

# Expected result

Colors are loaded for the choro-lethal

# Actual result

An error is raised because fetching SQL contains empty values in column placeholders

@coyle5280 can you guess where this is coming from?

**Comment by coyle5280** [comment]
Let me know what you think of the changes.  If you don't like this implementation we can talk about how to do it differently. There are a couple of different options.
