### ISSUE TITLE
[Aliases] "Merge -> Column join" modal doesn't show aliases

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#173]
## Context

When using the `bbg_pro_ui` feature flag, a user is presented with a "Merge" option on the side panel in "Edit mode" view for a dataset. One way to perform a "Merge" option is through "Column join".

## STR

1. Open a dataset in "Edit mode"
2. Click on "Merge" option in side panel
3. Click on "Column join"
4. Expand the drop down menu to choose from available datasets

## Expected result

All datasets and they're columns (when selected) show aliases if available.

## Actual result

Original dataset names and column names are shown instead of their aliases.

Here's a screen capture:

<img width="1000" alt="screen shot 2017-06-15 at 18 36 56" src="https://user-images.githubusercontent.com/4222826/27192448-b40425e6-51fb-11e7-8dbc-709243e4b8a7.png">

## SOW

Changes should be made so that the "Merge -> Column join" modal can display the column's aliases.

**Comment by gfiorav** [comment]
Hi @coyle5280 ,

What's the status on this issue?

**Comment by coyle5280** [comment]
Still working on this one.  All the code from the other branch has been moved over and looks good.  The spatial merge and column merge use some of the same files and one can not be updated without updating the other.  I am working updating the spatial merge side of things now.  I need to know how you want the table names displayed?  Do we show them the alias name or the original name or a combo of both?

**Comment by gfiorav** [comment]
For the use with aliasing capabilities, let's show both: `alias (original)`

For the rest just the alias
