### ISSUE TITLE
[Aliases] Georeferencing modal doesn't show aliases for column names

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#175]
## Context

When using the `bbg_pro_ui` feature flag, a user is presented with a "georeference" option by clicking on the yellow "GEO" label for the `the_geom` column in "Edit mode" view for a dataset. Upon clicking this label, a user is presented with several types of georeferencing options (Lat/Long Columns, City Names, Admin. Regions, Postal Codes, IP Addresses, Street Addresses) , all of which require the user to select columns containing relevant information for georeferecing from several dropdowns.

## STR

1. Open a dataset in "Edit mode"
2. Click on "GEO" label for the `the_geom` column (make sure all values in this column are set to NULL first)
3. For any column select dropdown in any of the tabs (Lat/Long Columns, City Names, Admin. Regions, Postal Codes, IP Addresses, Street Addresses) in the modal

## Expected result

The dropdown shows aliases for aliased column names.

## Actual result

The dropdown shows the original column names instead of the aliased ones.

Here's a screen capture:

<img width="979" alt="screen shot 2017-06-15 at 18 43 51" src="https://user-images.githubusercontent.com/4222826/27192884-3bc2813e-51fd-11e7-9c3a-dafb91d86e54.png">

## SOW

Changes need to be made so that the georeferencing modal (and all it's tabs: Lat/Long Columns, City Names, Admin. Regions, Postal Codes, IP Addresses, Street Addresses) display aliased column names in their dropdown selectors for columns.

**Comment by coyle5280** [comment]
@gfiorav I am close to finishing this one up but I need good csv files or something similar to test each geocoding case with.  Can you help with this?  We need one with a lat long column. One with city names and possibly region and country. One with region name and possible country. One with postal codes and possibly country. One with ip addresses. And finally one with street address.  I will look for these tomorrow but again if you can find some it would help.  Thanks!!

**Comment by gfiorav** [comment]
Hey @coyle5280, this one is my favourite!

http://spatialkeydocs.s3.amazonaws.com/FL_insurance_sample.csv.zip

Try clearing out the `the_geom` column if you want to geocode (`UPDATE fl_insurance_sample SET the_geom = NULL`).

**Comment by gfiorav** [comment]
Hey @coyle5280, could you provide an estimate for this one?

**Comment by coyle5280** [comment]
@gfiorav I will try to have the testing done on this one tomorrow the 2nd.

**Comment by coyle5280** [comment]
@gfiorav I have tested this as much as I can.  Let me  know what you think and if you see anything that needs changing.  Thanks!
