### ISSUE TITLE
[Aliases] Aliased column name stored in wizard

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#178]
## Context

Some wizards have a column dropdown where users can select a column to apply style by. It's been observed that when the default chosen column is aliased, this alias is stored as a column name in the wizard, generating errors.

## STR

0. Create a dataset subject to using a "Category" wizard
1. Make sure the first column (default for the wizard) is aliased
2. Choose a "Category" wizard for the dataset style

## Expected result

The default column is the aliased column, and everything works fine.

## Actual restul

The default column is the aliased column, but the value passed on is that one instead of the original column name.

## SOW

Changes should be made so that original name is passed on from a dropdown selector even when the aliased value is shown.

## Extra

This is the original report, containing some clues as to where the issue is located:
```
This issue occurs when a column with an alias is the default value for the form which picks columns for the category wizard.

As per [FormSchema#_fillCoulmns](https://github.com/bloomberg/cartodb/blob/blp_dev/lib/assets/javascripts/cartodb/models/wizard.js#L106), the `value` member within `FormSchema`, which indicates the default selection of that form field if nothing is previously selected, will be the alias of the first column in extra (if an alias exists).

This `value` will ultimately be used to populate the form, and will in turn be saved into a `WizardProperties` object.  This happens through the following code path when activated the categories widget after setting:
* [CartoCSSWizard#_onWizardClick](https://github.com/bloomberg/cartodb/blob/blp_dev/lib/assets/javascripts/cartodb/table/menu_modules/carto_wizard.js#L50)
* [WizardProperties#active](https://github.com/bloomberg/cartodb/blob/blp_dev/lib/assets/javascripts/cartodb/models/wizard.js#L447)
  * See [WizardProperties#defaultStyleForType](https://github.com/bloomberg/cartodb/blob/blp_dev/lib/assets/javascripts/cartodb/models/wizard.js#L391) for how `geomForm` is populated with the `property` field which is ultimately used to fill the form.

Note that an aliased column must appear first in the sorted `extra` list for the issue to occur.  If the category dropdown column is subsequently changed by the user, it appears the alias is overwritten and saved correctly.
```

**Comment by coyle5280** [comment]
PR #180 should correct the issue.  Please test before pushing to Bloomberg. I tried to test all possible use cases but may have missed one.  My testing showed no alias names in the wizard properties and the wizards them selves were showing alias names where applicable but using original names.

**Comment by gfiorav** [comment]
Thanks.

I have updated the branch with some new stuff from blp_dev and couldn't reproduce the problem even before this patch. Did you reproduce it on `source` before preparing the fix?
