### ISSUE TITLE
[Filters] Remove `This column has one unique value` pop-up

### ISSUE THREAD

**Issue by alissarose** [cartodb-org/cartodb#184]
### context
In `faceted search` when selecting a column with one value, a message appears directly below the column name that says `This column has one unique value` -- this should be removed per clients request; all other messages are okay.

### approach
Delete message / editor leftover

**Comment by alissarose** [comment]
back to dev --> see comment in [PR](https://github.com/cartodb-org/cartodb/pull/192)

**Comment by coyle5280** [comment]
@alissarose @gfiorav 
When a user selects a numerical column with only on value the histogram is not displayed because there is no range to display. If the single value message is not shown then what should be shown to the user? You cant make a histogram with no range of values.   
![capture](https://user-images.githubusercontent.com/11877788/31824798-60d16700-b56d-11e7-849d-cf8366772673.JPG)

**Comment by alissarose** [comment]
@coyle5280 i'll follow up BB and let you know

**Comment by alissarose** [comment]
@coyle5280 - BB wants to know if they can just have a histogram with one number? in my mind, this does not make sense...in the code does this make sense?

**Comment by coyle5280** [comment]
@alissarose My gut feeling says no. I believe that it would require a major update to the histogram code in order to handle that but let me see what would happen if the current code tried to create one with a single value. I will post an update tomorrow.  Thanks!

**Comment by coyle5280** [comment]
@alissarose Would this be acceptable? The adjustment bars do not show because they are technically on top of each other.  
![capture](https://user-images.githubusercontent.com/11877788/31957770-0aed9294-b8ad-11e7-83e1-2531adb762d2.JPG)

**Comment by alissarose** [comment]
that looks good to me, and the behavior seems appropriate.

let me verify with BB and I will update ASAP

**Comment by alissarose** [comment]
last question -- would it be possible to force single value numbers into a numeric list rather than histogram? (multi-select list, with values)

This means, *all* results with only one value will appear as a list (as below, with `one unique value` no longer appearing)
<img width="459" alt="screen shot 2017-10-25 at 5 46 28 pm" src="https://user-images.githubusercontent.com/6743887/32025043-b9f4f49e-b9ac-11e7-95bc-1e91906e1f38.png">

**Comment by coyle5280** [comment]
@alissarose I am not sure what the end result of that would be. I am sure that we could force it to try and display the numerical value but it was never intended to do that so I am unsure of all the consequences.  Let me try it out and see what I get and Ill get back to you with more info.

**Comment by alissarose** [comment]
hey @coyle5280 - I think we should stick to what's feasible in the existing code here. let's go ahead with the single value histogram.
