### ISSUE TITLE
[Filters] Sort order dropdown appearing before filter added 

### ISSUE THREAD

**Issue by alissarose** [cartodb-org/cartodb#188]
### context
In the multi-field select filter (records 210+) a user is prompted to sort the order of results before the filter has been applied. The client does not want this option to appear until the filter has been added since there are datasets that are not displayed due to # of records

### approach
Remove the default order option from appearing when records >210;  re-render can present difficulties

**Comment by coyle5280** [comment]
@alissarose 
If a user removes all items from the section filter (remote filter with over 220+ options) and they had set a sort of `a to z`. If they remove all items and the sort disappears should it reset back to `default order` or should it stay at `a to z` when it reappears (when they select an item)?

**Comment by gfiorav** [comment]
It looks like the PR for this issue hasn't been referenced here (nor this issue from the PR) since I don't see and linking messages. Could you link it, @coyle5280 ?

**Comment by alissarose** [comment]
I think I connected it  - https://github.com/cartodb-org/cartodb/pull/201

cc/ @gfiorav

**Comment by gfiorav** [comment]
That one says #190, not #188 🙈

**Comment by alissarose** [comment]
yeah, but i think it's the right one?

the PR for #190 is https://github.com/cartodb-org/cartodb/pull/195
