### ISSUE TITLE
[Filters] Highlight search term in list of results (mulit-select autocomplete)

### ISSUE THREAD

**Issue by alissarose** [cartodb-org/cartodb#189]
### context
When a user is searching for a record within a field, they are currently shown matching results however the _exact_ match is not clear. For example, when the user types `Th` all records beginning with Th will appear but those two characters are not distinguished in any way from the rest of the string. 

### approach
When a user is searching records, the results that appear in the autocomplete should have the corresponding letters appear as either `highlighted` or _bold_ (whichever is the preferred class change)

**Comment by alissarose** [comment]
just want to follow up on this - @coyle5280 were you able to determine if this is a backend issue?

cc/ @gfiorav

**Comment by coyle5280** [comment]
@alissarose No this will be done on the client side.  The possible server side fix was in regards to #190 but that was not a sever side issue and should be fixed in PR #195
