### ISSUE TITLE
[Filters] Cursor should not change when hovering over lists

### ISSUE THREAD

**Issue by alissarose** [cartodb-org/cartodb#191]
### context
When a user hovers over selectable values in lists, the cursor changes

### approach
The cursor should remain the same regardless of where it hovers; change CSS directive to enforce this

**Comment by coyle5280** [comment]
@alissarose Is this for the entire site or just for the filters section? As it stands now the cursor will change when it hovers on the table, table headers, filters, etc. It would make sense that the cursor would never change and always stay the same icon but need more clarification before i start on this one.

**Comment by alissarose** [comment]
@coyle5280 - please just remove it for the `Filters Section`, all other instances can remain

thanks!
