### ISSUE TITLE
[Aliases] Delete dataset not showing alias

### ISSUE THREAD

**Issue by alissarose** [cartodb-org/cartodb#197]
### context
When a user (mapsdata or regular) goes to delete an Aliased dataset, the alias does not appear in the warning message

### approach
The error message format should be: “Aliased name (original name)”

**Comment by alissarose** [comment]
hi @coyle5280 when going through alias acceptance testing, the one outstanding issue we found was that when deleting a dataset - the alias does not appear.

let me know if you have any questions or need further guidance.

**Comment by coyle5280** [comment]
@alissarose The alias name was appearing (for me at least) in the delete page. I added the original name in parenthesis to the delete confirmation page.  Please review and let me know if I missed something. This change was tested and working before the recent updates to the filters_update branch.  The recent update introduced some css variables that I do not have.  I will get with @gfiorav to get that fixed but should not affect this change.  Thanks!

**Comment by gfiorav** [comment]
Hey @alissarose 

I was reviewing the PR and it seems like there's been some confusion here (my bad!). What can't happen under any circumstance is that a user sees the original name of the dataset. Only a few privileged users can see the original name, all others should never know they're looking at an alias.

@coyle5280 there's a module that I wrote for this. It takes a user, an original name and an alias and figures out what to show. You can use it here, it's https://github.com/cartodb-org/cartodb/blob/aliases-signoff/lib/assets/javascripts/cartodb/common/view_helpers/alias_presenter.js

**Comment by coyle5280** [comment]
@gfiorav I have updated the code to use the alias_presenter module. Thanks!

**Comment by alissarose** [comment]
closing --> PR was merged 2 weeks ago :D
