### ISSUE TITLE
Static map on published map and move zoom back 1

### ISSUE THREAD

**Issue by mbforr** [cartodb-org/cartodb#24]
@javisantana

**Comment by javisantana** [comment]
these are two things:
- move zoom back 1 zoom level <- this should be pretty quick
- static map on published map requires:
  - changing the viz.json so overlays attribute contains the inset map: https://github.com/CartoDB/cartodb/blob/bbg_production/app/models/visualization/vizjson.rb#L205
  - add support for that overlay in cartodb.js, like this https://github.com/CartoDB/cartodb.js/blob/develop/src/vis/overlays.js#L58

cc @CloudNiner @flibbertigibbet

take into account the branch to add this is: https://github.com/cartodb/cartodb/tree/bbg_production

**Comment by CloudNiner** [comment]
Fixed move zoom back one level in https://github.com/cartodb-org/cartodb/commit/4243942f81abb323547829a74f3011f9a042ff9c

**Comment by CloudNiner** [comment]
This feature should be complete as of cartodb-org/cartodb.js#5 and #53.

**Comment by jbranigan** [comment]
@mbforr This can be closed?

**Comment by mbforr** [comment]
All good.

On Thu, Jul 14, 2016 at 11:07 AM, jbranigan notifications@github.com
wrote:

> @mbforr https://github.com/mbforr This can be closed?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/cartodb-org/cartodb/issues/24#issuecomment-232693496,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEmtLPTOd_nSwPh5JX9mf7n25YI_RD8Yks5qVlDLgaJpZM4IaseE
> .

## 

_Matt Forrest_
Client Success Manager

_CARTO_
201 Moore St, Brooklyn, NY, 11206
P: (917) 463-3232 x7508
C: (612) 325-8470
carto.com http://www.carto.com/
