### ISSUE TITLE
[Filters] Wrong background color in dashboard side panel

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#248]
## Context

It seems that the dashboard left panel has a wrong background color in the `filters-update` branch.

@coyle5280 could you check what change broke this? I know there's been some CSS manipulation.

Thanks!

**Comment by gfiorav** [comment]
Actually never mind! Found it, bad merge on my side. Thanks!

**Comment by alissarose** [comment]
😅👍🏼
