### ISSUE TITLE
Title and description formatting updates

### ISSUE THREAD

**Issue by mbforr** [cartodb-org/cartodb#25]
Disable Drag / Drop and Cross-hair  
Remove Duplicate
Remove Bring to Front
Remove Bring to Back
Not showing on Static Export
Not showing on Published Map (Interactive)

@javisantana

**Comment by jbranigan** [comment]
Disable actions set, work on export

**Comment by CloudNiner** [comment]
Fixed:
- Remove duplicate
- Remove bring to front
- Remove bring to back
- Not showing on static export

In #33 and #36

**Comment by CloudNiner** [comment]
It looks like we may still need to do the 'disable drag/drop and crosshair' item. I don't recall if that was ever done. Otherwise this feature should be complete.

**Comment by mbforr** [comment]
Perfect!

On Thu, Jun 16, 2016 at 9:32 AM, Andrew Fink notifications@github.com
wrote:

> It looks like we may still need to do the 'disable drag/drop and
> crosshair' item. I don't recall if that was ever done. Otherwise this
> feature should be complete.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/cartodb-org/cartodb/issues/25#issuecomment-226485534,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEmtLMZJKKD7DhXc_p3VdT7z78ji9M2yks5qMVBRgaJpZM4IasfC
> .

## 

_Matt Forrest_
Client Success Manager

_CartoDB_
201 Moore St, Brooklyn, NY, 11206, USA
T: (612) 325-8470 Skype: mbforr
W: www.cartodb.com

Live sessions to learn CartoDB http://cartodb.com/webinars/

**Comment by CloudNiner** [comment]
Took a look at this just now, I'm able to drag the description box around, but when I release it reverts to the proper snapped position. Was not able to get a crosshair to show. I believe this task is complete, closing.
