### ISSUE TITLE
Updates to cancel dataset upload

### ISSUE THREAD

**Issue by mbforr** [cartodb-org/cartodb#26]
Intermittently worked
No loading or progress bar, just hangs until it happens. 

@javisantana

**Comment by flibbertigibbet** [comment]
Could you please provide some steps to reproduce or a description of what what happened for "intermittently worked?"

Regarding not having a loading or progress bar: cancelling stops the UI polling immediately, so from the user standpoint it should appear to cancel instantly. What hangs, and what is the desired UI?

**Comment by CloudNiner** [comment]
@mbforr @javisantana can one of you address the above comment?

**Comment by mbforr** [comment]
All I had was that it sort of hung there sometimes and sometimes it worked.
The main thing was that when cancel was hit is that the cancel dialogue
held there for a while sometimes. We weren't able to directly replicate
that though.

On Thu, Jun 16, 2016 at 9:20 AM, Andrew Fink notifications@github.com
wrote:

> @mbforr https://github.com/mbforr @javisantana
> https://github.com/javisantana can one of you address the above
> comment?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/cartodb-org/cartodb/issues/26#issuecomment-226482563,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEmtLI_kVPjtVceJsPfNRjVNI5qA0orLks5qMU2RgaJpZM4Iasf9
> .

## 

_Matt Forrest_
Client Success Manager

_CartoDB_
201 Moore St, Brooklyn, NY, 11206, USA
T: (612) 325-8470 Skype: mbforr
W: www.cartodb.com

Live sessions to learn CartoDB http://cartodb.com/webinars/

**Comment by CloudNiner** [comment]
After a discussion with Matt, this maybe related to delay in the PUT request to cancel the job. We're going to close this for now, future improvements could include a spinner until the UI receives a 200 back on the request to cancel.
