### ISSUE TITLE
Title and Description formatting

### ISSUE THREAD

**Issue by jbranigan** [cartodb-org/cartodb#4]
For the fixed title option in a visualization, the client would like several options for formatting the fixed title. The ideal workflow would be to add an ‘edit’ button next to the title and description that when clicked would open up the same editing options as the Annotations/Text items that float in a visualization.

**Comment by mbforr** [comment]
![screen shot 2016-02-10 at 11 38 07 am](https://cloud.githubusercontent.com/assets/4828460/12954114/401c33e6-cfeb-11e5-873d-3b6e91e42c79.png)
