### ISSUE TITLE
Export Adjustments 

### ISSUE THREAD

**Issue by jbranigan** [cartodb-org/cartodb#45]
(Sprint C)
Multiple improvements to the way maps are exported and to the UI controls around the image export. The design is based off the doc ‘MAPS_Exprot_Flow_v6’. Requirements are listed below:
- [x] Move Export to top right corner
- [x] Move Publish to Actions (edit dropdown), and label as "Get Link". Change from full screen display to floating pop-up.
- [x] Move Export options to replace toolbar options when export preview is activated
- [x] Add four controls to top menu bar, destination, size, save, cancel. 
  - Destination 
    - [x] Two options: AVMM and Local
    - [x] Default: AVMM
    - [x] Should be configurable so that dropdown options can be flagged as internal vs. External, etc...
  - Size
    - [x] Sizes: Small, Medium, Large, Custom
    - [x] Bounding box to display solid border when standard size option is selected, size should not be editable
    - [x] Width and Height controls to display when Custom Size is selected (more detail in spec)
  - [x] Save
  - [x] Cancel
- [x] Confirmation pop-up message to appear showing map preview, title, description, and copy-only ID (Bloomberg to populate ID field)
-  ~~Download location description to pop-up when local destination is selected and filetype to default to PNG.~~
-  ~~Map Title to pre-populate as File Name~~

**Comment by CloudNiner** [comment]
This PDF contains the wireframes for this task:
[MAPS_Export_Flow_v7.pdf](https://github.com/cartodb-org/cartodb/files/318447/MAPS_Export_Flow_v7.pdf)

In the local export section, we are not doing the local 'Save as' dialog. The application will continue to use its current behavior (download to default location based on browser settings).

**Comment by CloudNiner** [comment]
@javisantana when we discussed this earlier you mentioned some hook that calls out to save the image to AVMM and return the image ID. Does that hook currently exist in the this repo? If it does not, can you provide the method signature so we can mock it out and use it in the code we'll be writing?

**Comment by javisantana** [comment]
You just need to setup 

```
static_image_upload_endpoint: '/upload_endpoint_url'
```

in the app_config.yml. That will enable the workflow where the image is posted to that url

**Comment by sharph** [comment]
@javisantana @mbforr 

Our working branch for this issue is `feature/export-adjustments-working`.

![avmm_saved](https://cloud.githubusercontent.com/assets/539905/16534568/b65a8840-3fae-11e6-9e5b-63957379e1c7.png)

![get_link](https://cloud.githubusercontent.com/assets/539905/16534582/d4e66c84-3fae-11e6-870f-8693dd8c9080.png)

This is our temporary way to trigger an AVMM image export:
![temporary](https://cloud.githubusercontent.com/assets/539905/16534608/027612c6-3faf-11e6-8b2a-db780dfc388b.png)

**Comment by flibbertigibbet** [comment]
Also on feature/export-adjustments-working, toolbar and preset sizes or custom size:

### Default small size:

![image](https://cloud.githubusercontent.com/assets/960264/16534889/2fe246ba-3fb1-11e6-96c5-3a4a103f83df.png)

### Custom size option, with resizer:

![image](https://cloud.githubusercontent.com/assets/960264/16534895/40385cd4-3fb1-11e6-9020-77e09201c45a.png)

**Comment by flibbertigibbet** [comment]
Now referencing: 
[MAPS_RemoveToolbar_v4.pdf](https://github.com/cartodb-org/cartodb/files/348219/MAPS_RemoveToolbar_v4.pdf)

**Comment by flibbertigibbet** [comment]
Custom export image resizer is hooked up to the text widgets now on the export working branch:
![image](https://cloud.githubusercontent.com/assets/960264/16633494/9f6e8c7a-4397-11e6-9087-e24339f7d3bc.png)

Still have an outstanding issue with model size initialization to resolve.

**Comment by flibbertigibbet** [comment]
![image](https://cloud.githubusercontent.com/assets/960264/16658886/143dacb8-4436-11e6-9b12-e7521d57c7ed.png)

**Comment by flibbertigibbet** [comment]
@mbforr The work for this issue has been merged into `bbg_production`.
