### ISSUE TITLE
Overview Map

### ISSUE THREAD

**Issue by jbranigan** [cartodb-org/cartodb#7]
Add an option for an Overview Map into the editor that can be turned on and off via an option in the ‘Options Tab’. This would need to update using the current base map that is selected.

**Comment by mbforr** [comment]
![screen shot 2016-02-10 at 11 38 25 am](https://cloud.githubusercontent.com/assets/4828460/12954073/1687e3c2-cfeb-11e5-9b5b-ee33a5b4837c.png)

**Comment by mbforr** [comment]
I know we talked about the static image export of the inset map - any further thoughts on that?

**Comment by CloudNiner** [comment]
For the last bullet point "World Countries Borders to appear": Should the world borders only show up on the inset map?

**Comment by mbforr** [comment]
Yes correct - only on the overview map would the world borders appear when the base map is a plain color.

**Comment by CloudNiner** [comment]
What does the UI look like for "Ability to place inset map in any corner"? There is no existing feature set for this.

**Comment by mbforr** [comment]
Ideally it would be draggable - otherwise could there be some sort of dropdown where we can designate a corner. Is one easier than the other?

**Comment by CloudNiner** [comment]
I don't think one of those is necessarily harder than the other.

If it were draggable, where would you click to start the dragging interaction? The map already intercepts draggable events in that overlay. I suppose there could be a small box in one of the overlay corners that handles this interaction instead and cancels the map drag beneath it.

If the control is draggable, presumably whenever you end dragging it would snap to the proper position in the closest corner of the screen?

If a dropdown, what would that look like?

**Comment by CloudNiner** [comment]
Also, where would a "World Borders" layer be hosted such that I can use it from within the inset leaflet map? It would need to be a TileLayer or with more work, geojson.

**Comment by mbforr** [comment]
For the interactivity I think drag and drop would be best. If a user hovers
over the inset map and the cursor changes to the four arrow cursor that
should work. I think if there is a way to signal that with a hover event
that would be good too.

And yes the snapping to the closest corner of the screen would be perfect.

On Tue, Feb 16, 2016 at 5:26 PM, Andrew Fink notifications@github.com
wrote:

> Also, where would a "World Borders" layer be hosted such that I can use it
> from within the inset leaflet map? It would need to be a TileLayer or with
> more work, geojson.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cartodb-org/cartodb/issues/7#issuecomment-184900083.

## 

_Matt Forrest_
Account Manager

_CartoDB_
201 Moore St, Brooklyn, NY, 11206, USA
T: (612) 325-8470 Skype: mbforr
W: www.cartodb.com

Live sessions to learn CartoDB http://cartodb.com/webinars/

**Comment by mbforr** [comment]
For the world borders just let me know what would be best and I can work on
getting that to you.

On Tue, Feb 16, 2016 at 5:54 PM, Matt Forrest mforrest@cartodb.com wrote:

> For the interactivity I think drag and drop would be best. If a user
> hovers over the inset map and the cursor changes to the four arrow cursor
> that should work. I think if there is a way to signal that with a hover
> event that would be good too.
> 
> And yes the snapping to the closest corner of the screen would be perfect.
> 
> On Tue, Feb 16, 2016 at 5:26 PM, Andrew Fink notifications@github.com
> wrote:
> 
> > Also, where would a "World Borders" layer be hosted such that I can use
> > it from within the inset leaflet map? It would need to be a TileLayer or
> > with more work, geojson.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/cartodb-org/cartodb/issues/7#issuecomment-184900083.
> 
> ## 
> 
> _Matt Forrest_
> Account Manager
> 
> _CartoDB_
> 201 Moore St, Brooklyn, NY, 11206, USA
> T: (612) 325-8470 Skype: mbforr
> W: www.cartodb.com
> 
> Live sessions to learn CartoDB http://cartodb.com/webinars/

## 

_Matt Forrest_
Account Manager

_CartoDB_
201 Moore St, Brooklyn, NY, 11206, USA
T: (612) 325-8470 Skype: mbforr
W: www.cartodb.com

Live sessions to learn CartoDB http://cartodb.com/webinars/

**Comment by mbforr** [comment]
I know we also discussed including that in the image export. Any idea how difficult that would be?

**Comment by CloudNiner** [comment]
Hovering over the entire inset map and triggering the click/drag from there conflicts with "Ability to use the inset map to navigate the main map". 

See #16 for a current screenshot of the feature, there is a grey box in the top right of the inset map. Would it be acceptable for the drag and drop to be triggered on a click on that element instead of the whole map?

re: World Borders -- Ideally a leaflet accessible tile layer would be best, e.g. `http://{s}.somedomain.com/world-borders/{z}/{x}/{y}.png`, but a static geojson file sitting in an S3 bucket or some other publicly accessible url would work too.

re: image export -- Haven't had a chance to look into it yet, will do so tomorrow!

**Comment by mbforr** [comment]
1) Grey element is perfect - looks great!

2) Let me see what we can do there

3) Thanks!

**Comment by CloudNiner** [comment]
Great. I'll clean up the gray element, add an image and make that draggable. 

Will update you by the end of today on the status of the image export.

**Comment by mbforr** [comment]
@CloudNiner So I am checking about this now to confirm but we may have them create a base map to use specifically for the overview map so it fits in with the design of the other base maps and in the interim we can use Positron as the default for maps with colors selected.

**Comment by CloudNiner** [comment]
That sounds fine to me. Just let me know what you guys decide and we can implement.

As for the draggable control, I've hit a few road blocks relating to dragging and I'm not sure how to solve them without significant extra time. So I'm going to swap to a dropdown control triggered via click from the top left of the inset map control if that's acceptable.

**Comment by CloudNiner** [comment]
Also just looked into adding the inset map to the "Export Image" feature. I don't think this is feasible within the current scope. Unless I'm mistaken, it looks like both the regular and advanced image export options on that feature call out to windshaft. If you'd like a more detailed answer, I'd probably need to talk with a cartodb developer or two and deep dive into the windshaft code to figure out a plan to see if its feasible as well as a time estimate.

**Comment by mbforr** [comment]
1) Dropdown sounds good
2) For the export image let's look at what that would take. I can work on setting that meeting up but make sure to mention something in Slack as well

**Comment by CloudNiner** [comment]
Here's what the dropdown looks like ATM, let me know if you'd like to make any changes:
![bb-inset-1](https://cloud.githubusercontent.com/assets/1818302/13150426/b8c54492-d633-11e5-8525-92aa5e3fccae.png)
![bb-inset-2](https://cloud.githubusercontent.com/assets/1818302/13150427/b8e6eb24-d633-11e5-941d-f514197195af.png)

**Comment by CloudNiner** [comment]
Ok on image export.

**Comment by mbforr** [comment]
Dropdown looks perfect!
