### ISSUE TITLE
Dismiss Banner

### ISSUE THREAD

**Issue by jbranigan** [cartodb-org/cartodb#8]
Add a dismiss option on the dialogue that pops up when a filter is applied

**Comment by mbforr** [comment]
If you could send a screen shot of this feature that would be great (I'll post this on the other open issues too.)

**Comment by jbranigan** [comment]
When between map and data view, keep the banner dismissed. When going out to map list and coming back to map, banner can show again

**Comment by flibbertigibbet** [comment]
Screenshot of the text added in #18:

![image](https://cloud.githubusercontent.com/assets/960264/15195141/860214ac-1794-11e6-8f60-3f23ccf68cac.png)

**Comment by CloudNiner** [comment]
@mbforr this should work as requested now.
