### ISSUE TITLE
Cancel Uploads

### ISSUE THREAD

**Issue by jbranigan** [cartodb-org/cartodb#9]
Add a cancel button to stop an upload attempt

**Comment by flibbertigibbet** [comment]
Re-opening for confirmation

**Comment by mbforr** [comment]
If you could send a screen shot of this feature that would be great (I'll post this on the other open issues too.)

**Comment by flibbertigibbet** [comment]
No UI changes happened for this one; it just re-uses the existing cancellation button that would previously disappear once the upload actually started.

![image](https://cloud.githubusercontent.com/assets/960264/14087172/a5293416-f4f6-11e5-80fa-ea54c758527d.png)
